### ISSUE TITLE
Seperate files inside post directory to help organization

### ISSUE THREAD

**Issue by sonukuldeep** [alxshelepenok/lumen#1293]
**Is your feature request related to a problem? Please describe.**
At present only a single file is allowed inside posts/post_name/index.md. Is it possible to have other files inside this post_name folder to help organize the documentation better? Like the index.md page becomes the parent and all sub files become children. 

**Describe the solution you'd like**
In the front matter we could have a variable set to declare a file as parent. This files gets displayed. Other files have a variable that describes them as children. These files do not get rendered directly instead they get rendered inside the parent when imported somehow.

**Comment by alxshelepenok** [comment]
Probably a late reply, but I just looked and see that you can use child pages at the moment.

You can use a query to check existing pages:
```
query Query {
  allMarkdownRemark {
    edges {
      node {
        id
        fields {
          slug
        }
      }
    }
  }
}
```

You can also use slug to specify any path (if it is not there, everything should be ok too):

![Screenshot_2024-12-02_23-30-16](https://github.com/user-attachments/assets/6e26b32b-a80d-4ad8-8ac5-7b466072b5b3)
