### ISSUE TITLE
KebabCase utils implementation differ over two files 

### ISSUE THREAD

**Issue by anubhavsrivastava** [alxshelepenok/lumen#1597]
**Describe the bug**
KebabCase here util -> https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/internal/gatsby/utils/to-kebab-case.ts
KebabCase here util -> https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/utils/to-kebab-case.ts

Both have slight different implementation result in different output.

**To Reproduce**
Have a category post as PackageManager
the page will be generated as `/packagemanager` while the link in categories link will be `/package-manager`

**Expected behavior**
consistent path should be generated

**Screenshots**

**Desktop (please complete the following information):**
 agnostic

**Smartphone (please complete the following information):**
agnostic

**Additional context**

**Comment by alxshelepenok** [comment]
It was fixed in one of the latest pr.
