### ISSUE TITLE
Include a static html file

### ISSUE THREAD

**Issue by charles-hood** [alxshelepenok/lumen#1742]
How can I include a static html file in my Lumen blog?
I have an html file that is generated by a program that includes an html table that I'd like to post for reference

**Comment by maxgrok** [comment]
Use markdown in your post to represent the table. That should work. Use [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) as a cheatsheet for how to form a table in the Markdown inside your post.
