### ISSUE TITLE
Set custom favicon

### ISSUE THREAD

**Issue by pakjiddat** [alxshelepenok/lumen#1985]
**Is your feature request related to a problem? Please describe.**
I would like to customize the favicon file

**Describe the solution you'd like**
I would like to be able to set the favicon icon file

**Describe alternatives you've considered**
One option is to use the default favicon file that is auto generated by the site. However I would like to use a custom favicon file

**Comment by alxshelepenok** [comment]
You can change it here - [#L159]( https://github.com/alxshelepenok/lumen/blob/main/gatsby-config.ts#L159)
